imports:
  - path: network.jinja
  - path: instance.jinja
  - path: nlb.jinja
resources:
- name: network
  type: network.jinja
  properties:
    ipv4Range: 10.10.0.0/16
    region: us-east1
    subnets:
      - range: 10.10.1.0/24
        name: network-subnet1-useast1b
      - range: 10.10.2.0/24
        name: network-subnet2-useast1b
      - range: 10.10.3.0/24
        name: network-subnet3-useast1c
- name: network-us-vm11
  type: instance.jinja
  properties:
    zone: us-east1-b
    device_name: vm11
    machineType: n1-standard-1
    item_name: network-us-vm11
    subnetwork: network-subnet1-useast1b
- name: network-us-vm21
  type: instance.jinja
  properties:
    zone: us-east1-b
    device_name: vm21
    machineType: n1-standard-1
    item_name: network-us-vm21
    subnetwork: network-subnet1-useast1b
- name: network-us-vm12
  type: instance.jinja
  properties:
    zone: us-east1-b
    device_name: vm12
    machineType: n1-standard-1
    item_name: network-us-vm12
    subnetwork: network-subnet2-useast1b
- name: network-us-vm22
  type: instance.jinja
  properties:
    zone: us-east1-b
    device_name: vm22
    machineType: n1-standard-1
    item_name: network-us-vm22
    subnetwork: network-subnet2-useast1b
- name: network-us-vm13
  type: instance.jinja
  properties:
    zone: us-east1-c
    device_name: vm13
    machineType: n1-standard-1
    item_name: network-us-vm13
    subnetwork: network-subnet3-useast1c
- name: network-us-vm23
  type: instance.jinja
  properties:
    zone: us-east1-c
    device_name: vm23
    machineType: n1-standard-1
    item_name: network-us-vm23
    subnetwork: network-subnet3-useast1c


- type: compute.v1.httpHealthCheck
  name: gcp-hc-one
  properties:
     port: 80
     requestPath: "/"
     checkIntervalSec: 60
- type: compute.v1.targetPool
  name: gcp-tp-one
  properties:
    region: us-east1
    instances: [ "https://www.googleapis.com/compute/v1/projects/lithe-bazaar-250717/zones/us-east1-b/instances/network-us-vm11","https://www.googleapis.com/compute/v1/projects/lithe-bazaar-250717/zones/us-east1-b/instances/network-us-vm12","https://www.googleapis.com/compute/v1/projects/lithe-bazaar-250717/zones/us-east1-c/instances/network-us-vm13" ]
    healthChecks: [$(ref.gcp-hc-one.selfLink)]
- type: compute.v1.forwardingRule
  name: gcp-fr-one
  properties:
    region: us-east1
    portRange: 80
    target: $(ref.gcp-tp-one.selfLink) 


- type: compute.v1.httpHealthCheck
  name: gcp-hc-two
  properties:
     port: 2100
     requestPath: "/"
     checkIntervalSec: 60
- type: compute.v1.targetPool
  name: gcp-tp-two
  properties:
    region: us-east1
    instances: [ "https://www.googleapis.com/compute/v1/projects/lithe-bazaar-250717/zones/us-east1-b/instances/network-us-vm21","https://www.googleapis.com/compute/v1/projects/lithe-bazaar-250717/zones/us-east1-b/instances/network-us-vm22","https://www.googleapis.com/compute/v1/projects/lithe-bazaar-250717/zones/us-east1-c/instances/network-us-vm23" ]
    healthChecks: [$(ref.gcp-hc-two.selfLink)]
- type: compute.v1.forwardingRule
  name: gcp-fr-two
  properties:
    region: us-east1
    portRange: 2100
    target: $(ref.gcp-tp-two.selfLink) 
